### ISSUE TITLE
How to get a response body in fastapi-health as return

### ISSUE THREAD

**Issue by Divyadarshee** [Kludex/fastapi-health#1]
How do we response body and not just response headers in return as the route.py body only returns 200 and 503 response status codes only

**Comment by Kludex** [comment]
I'm going to try to make it more customizable this weekend. Do you have more in mind besides those two points (status and body)?

Thank you for the feedback! :)

**Comment by Divyadarshee** [comment]
great 👌 will surely look into it more🤓 and will let you know what more customization might be required

**Comment by Kludex** [comment]
I didn't have the time, I'm going to check it over this week. jfyk

**Comment by Divyadarshee** [comment]
Any updates on this 
also can this be used as a decorator ?

**Comment by Kludex** [comment]
How do you imagine the decorator usage?

P.S.: I'm going to work on this today.

**Comment by Kludex** [comment]
@Divyadarshee What do you think about this implementation? https://github.com/Kludex/fastapi-health/pull/2

**Comment by Divyadarshee** [comment]
Thanks for the work i tested those changes in my local and they are good if we are using the success_output or failure_output but if are sending a dict (as mentioned in point no-2 above) it give the following error 
`ValueError: dictionary update sequence element #0 has length 1; 2 is required`
i guess 
`output = dict(filter(lambda x: isinstance(x, dict), values))`
in this part once filter returns an object of filter the dict() is looking at it as a list of dict eg: [{"Health_status":"Healthy}, {...},{...},{...}]
I could be wrong so please correct me



> How do you imagine the decorator usage?
> 
> P.S.: I'm going to work on this today.

For this its more like the way it is implemented and has very little to do with as a requirement
so like currently it has to be implemented with first the methods being defined and then the app (object) for fastapi being created, unlike normally an object of fastapi is created and then the methods are defined and decorated with required decorators defining path and other aspects (still learning😓). So basically it is a good to have feature making it look more integrated with fastapi nothing else i guess (there could be more technical use of this or even disadvantages so not sure would like hear your reasons and would be happy to be corrected and educated🤓)
Once again thanks for the work. Great job👌

**Comment by Kludex** [comment]
About the error, I imagine that would happened hahaha I didn't tested that. But what I wanted to hear is about the logic itself. A single `**` is missing (I hope). I'll fix that later.

About the decorator, I'm not sure if I get it. Do you have a code snippet in mind as example?

**Comment by Kludex** [comment]
I've made it work. But... It has a corner case on which it doesn't work properly :) 

I'm going to think about another solution in the weekend.

**Comment by conradogarciaberrotaran** [comment]
Hi @Kludex, im also interested in outputs. Can you tell us about the corner case? maybe we can fix it

**Comment by Kludex** [comment]
What I considered a "corner case" is actually an expected behavior. I'm going to consider it more as feature than a bug.

It's documented on the `Advanced Usage` on this PR: https://github.com/Kludex/fastapi-health/pull/2

I'm going to merge and publish tomorrow. @conradogarciaberrotaran Feel free to take a look, as it looks you're interested :kissing:

**Comment by Kludex** [comment]
The status code becomes redundant in this case.

**Comment by conradogarciaberrotaran** [comment]
Not if you're using some automatic health check like in k8s. The output is for the developer only.

**Comment by Kludex** [comment]
I'm going to check that implementation tomorrow. Sorry for not replying sooner :sweat_smile: 

But I'm not convinced about the "fix" output. I'll try to create a way to add "template dictionaries".

**Comment by Kludex** [comment]
I've looked more closely into [py-healthcheck](https://github.com/ateliedocodigo/py-healthcheck/), and I agree we can use their ideas. But I don't agree with the default output.

I'll be working on the next days to adapt the code so we can add this "custom behavior", similarly at how they do, but with the current default. 

What do you think @conradogarciaberrotaran ?

**Comment by conradogarciaberrotaran** [comment]
@Kludex I think that's awesome. I'll be the first to use it on production :)

**Comment by Kludex** [comment]
I have something now. Can you check the `route.py` and the last test and let me know what do you think @conradogarciaberrotaran ? https://github.com/Kludex/fastapi-health/pull/2/files

**Comment by Kludex** [comment]
@conradogarciaberrotaran I'm going to merge it tomorrow, jfyk.

**Comment by Kludex** [comment]
This is now available on 0.4.0.
