### ISSUE TITLE
Allow `HEAD` request

### ISSUE THREAD

**Issue by perezzini** [Kludex/fastapi-health#18]
Hello,

I was wondering if this library can, somehow, allow `HEAD` requests. I can see that FastAPI, for the moment, does not automatically support `HEAD` method for `GET` routes (see: https://github.com/tiangolo/fastapi/issues/1773).

Thanks in advance.

**Comment by perezzini** [comment]
(Think this is important given that some healthcheck utils make `HEAD` requests, instead of `GET` requests by default)

**Comment by Kludex** [comment]
> I can see that FastAPI, for the moment, does not automatically support HEAD method for GET routes (see: https://github.com/tiangolo/fastapi/issues/1773).

If you go further on that issue, you'll see that I've implemented two PRs to add HEAD there. :sweat_smile:

You can just manually add the `methods=["GET", "HEAD"]`, there's nothing that needs to be added on the `fastapi-health` itself.

**Comment by perezzini** [comment]
Yes! Haven't noticed, sorry! 😅. Thanks for your reply @Kludex and for your contribution implementing fastapi-health.
