### ISSUE TITLE
Please add py.typed marker

### ISSUE THREAD

**Issue by dvarrazzo** [Kludex/fastapi-health#20]
Using fastapi-health, mypy reports "module is installed but missing library stubs or py.typed marker".

As fastapi is nicely typed, you can easily add a py.typed marker. It's enough to add an empty file called `py.typed` in the `fastapi_health` package directory, and to include it in the distribution.

I would provide a MR, but I have no idea how to do include the file in a project using `pyproject.toml` file. If there was a `setup.cfg` file, it would be enough to add a stanza such as:

```
[options.package_data]
fastapi_health = py.typed
```

**Comment by Kludex** [comment]
I need to add a "contribution guidelines", but just including the file `py.typed`, and `hatch build`.
