### ISSUE TITLE
Disallow Pydantic v2 until support is added

### ISSUE THREAD

**Issue by Harry-Lees** [Kludex/fastapi-health#30]
Currently, this library does not support Pydantic v2 however, there is no requirement laid out in the dependencies. Since the latest version of FastAPI (0.100.1 at the time of writing) still supports Pydantic v1, I think Pydantic v2 support can be disabled until explicitly supported.

**Comment by Harry-Lees** [comment]
Support for Pydantic v2 added in #32 making this issue redundant.

**Comment by Kludex** [comment]
I need to check the changes I've implemented since the last release. I think I've added too many stuff without a release? 🤔
