### ISSUE TITLE
async support

### ISSUE THREAD

**Issue by trondhindenes** [Kludex/fastapi-health#9]
it would be great if there was async support here, for example with something like this:
```
app.add_api_route("/health", health([sync_methods], async_health([async_methods])))
```
fastapi-health would take care of awaiting the `async_health` methods etc. My use case is that in my async-only fastapi app I have to implement async-in-sync wrappers in order to use fastapi-health as it is today.

**Comment by Kludex** [comment]
How's that? 🤔

https://github.com/Kludex/fastapi-health/blob/main/tests/test_health.py#L60-L68

**Comment by trondhindenes** [comment]
oh nice - i just assumed there was no async support since the example didn't mention it. Great! Thanks for the prompt response!

**Comment by Kludex** [comment]
PR welcome to improve the README with a better example, jfyk. :)
